[package]
name = "hyprws"
version = "0.1.0"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
serde = "1.0.164"
serde_derive = "1.0.164"
serde_json = "1.0.96"
strum = "0.24.1"
strum_macros = "0.24.3"
